### ISSUE TITLE
Do you still recommend hyper_binary over hyper_carray?

### ISSUE THREAD

**Issue by kocolosk** [GameAnalytics/hyper#12]
Noticed that you've got an undocumented C implementation in the repo now. The benchmark numbers for it look quite good. Do you still recommend hyper_binary as the standard choice?

**Comment by elverkilde** [comment]
We use both implementations in production at Game Analytics at the moment and the c implementation has been stable.

The only reason we are still using hyper_binary is that the NIF version cannot be shared between nodes. If that is not needed the c version is recommended for its performance.
