### ISSUE TITLE
One file is GPL, everything else is MIT?

### ISSUE THREAD

**Issue by JeetKunDoug** [GameAnalytics/hyper#15]
https://github.com/GameAnalytics/hyper/blob/master/c_src/hyper_carray.c#L5 claims the C implementation of `hyper_carray` as GPL, but the LICENSE file is MIT. Can you clarify which license this library falls under, and perhaps drop the GPL header from `hyper_carray.c` if the intent is for it to be MIT licenced?  For the moment, we're dropping the `hyper_carray` backend from our fork before shipping HLL support in Riak (as we're currently using the `hyper_binary` backend anyway). We originally found this because we ran into issues compiling `hyper_carray.c` on Solaris, one of our target operating systems.

**Comment by elverkilde** [comment]
That's not good. The C implementation was originally a separate project which was merged in and the license was probably forgotten.

I guess the preferred solution is to change the license to MIT. We will need permission from all contributors AFAIK. My permission is hereby given.

Can you submit a separate PR with the Solaris fix? It would be great to have that in.

cc @johannesh @chrisavl @cmdevries

**Comment by binarytemple-bet365** [comment]
Just for the point of clarity - https://github.com/GameAnalytics/hyper/blob/master/c_src/hyper_carray.c#L5 - that line says LGPL. Not to diminish the importance of a consistent license, but worth mentioning that LGPL code will not contaminate an entire codebase in the same manner as GPL licensed code.

**Comment by johannesh** [comment]
@elverkilde, go for the MIT for carray for this project :+1:

**Comment by renjith-ga** [comment]
Merged the pull request from @elverkilde  as the permission has been given by all three contributors @elverkilde @chrisavl and @johannesh to change license to MIT. Hence closing this issue.

**Comment by cmdevries** [comment]
LGTM
